BVA/BVA/Controllers/Admin/AdminWalletController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ECFBase.Models;
using ECFBase.Components;
using System.Data;
using System.Globalization;
using System.IO;
using System.Text;
using ECFBase.Resources;

namespace ECFBase.Controllers.Admin
{
    public class AdminWalletController : Controller
    {
        #region WalletAdjustment
        public ActionResult WalletAdjustment(string Username, string Type)
        {
            if (Session["Admin"] == null || Session["Admin"].ToString() == "")
            {
                return RedirectToAction("AdminLogin", "Admin", new {  });
            }

            int ok = 0;
            string msg = "";
            WalletAdjustmentModel model = new WalletAdjustmentModel();
            model.Username = Username;
            var dataset = MemberDB.GetMemberByUsername(Username, out ok, out msg);
            if (dataset.Tables[0].Rows.Count == 0)
            {
                Response.Write(Resources.OneForAll.OneForAll.msgInvalidUser1);
                return Json(string.Empty, JsonRequestBehavior.AllowGet);
            }

            DataRow memberDetails = dataset.Tables[0].Rows[0];

            model.Type = Type;

            if (Type == ProjectStaticString.RegisterwalletTopUp)
            {
                model.TypeResource = Resources.OneForAll.OneForAll.mnuRegisterTopUp;
                model.WalletBalanceTypeResource = "Register Point Balance";
                model.Nickname = memberDetails["CUSRINFO_NICKNAME"].ToString();
                model.CurrentWallet = float.Parse(memberDetails["CMEM_REGISTERWALLET"].ToString());
            }
            else if (Type == ProjectStaticString.CashwalletTopUp)
            {
                model.TypeResource = Resources.OneForAll.OneForAll.mnuCashTopUp;
                model.WalletBalanceTypeResource = "Cash Point Balance";
                model.Nickname = memberDetails["CUSRINFO_NICKNAME"].ToString();
                model.CurrentWallet = float.Parse(memberDetails["CMEM_CASHWALLET"].ToString());
            }
            else if (Type == ProjectStaticString.GoldPointTopUp)
            {
                model.TypeResource = "Gold Point TopUp";
                model.WalletBalanceTypeResource = "Gold Point Balance";
                model.Nickname = memberDetails["CUSRINFO_NICKNAME"].ToString();
                model.CurrentWallet = float.Parse(memberDetails["CMEM_GOLDPOINT"].ToString());
            }
            else if (Type == ProjectStaticString.MultiPointTopUp)
            {
                model.TypeResource = "Multi Point TopUp";
                model.WalletBalanceTypeResource = "Multi Point Balance";
                model.Nickname = memberDetails["CUSRINFO_NICKNAME"].ToString();
                model.CurrentWallet = float.Parse(memberDetails["CMEM_MULTIPOINT"].ToString());
            }
            else if (Type == ProjectStaticString.RPCTopUp)
            {
                model.TypeResource = "Repurchase TopUp";
                model.WalletBalanceTypeResource = "Repurchase Point Balance";
                model.Nickname = memberDetails["CUSRINFO_NICKNAME"].ToString();
                model.CurrentWallet = float.Parse(memberDetails["CMEM_REPURCHASEWALLET"].ToString());
            }
            else if (Type == ProjectStaticString.RMPTopUp)
            {
                model.TypeResource = "RMP TopUp";
                model.WalletBalanceTypeResource = "Register MP Balance";
                model.Nickname = memberDetails["CUSRINFO_NICKNAME"].ToString();
                model.CurrentWallet = float.Parse(memberDetails["CMEM_RMPWALLET"].ToString());
            }
            else if (Type == ProjectStaticString.ICOTopUp)
            {
                model.TypeResource = "ICO TopUp";
                model.WalletBalanceTypeResource = "ICO Point Balance";
                model.Nickname = memberDetails["CUSRINFO_NICKNAME"].ToString();
                model.CurrentWallet = float.Parse(memberDetails["CMEM_ICOWALLET"].ToString());
            }
            else if (Type == ProjectStaticString.CompanyTopUp)
            {
                model.TypeResource = "CRP TopUp";
                model.WalletBalanceTypeResource = "Company Register Point Balance";
                model.Nickname = memberDetails["CUSRINFO_NICKNAME"].ToString();
                model.CurrentWallet = float.Parse(memberDetails["CMEM_COMPANYWALLET"].ToString());
            }
            else if (Type == ProjectStaticString.TPTopUp)
            {
                model.TypeResource = "TP TopUp";
                model.WalletBalanceTypeResource = "Travel Point Balance";
                model.Nickname = memberDetails["CUSRINFO_NICKNAME"].ToString();
                model.CurrentWallet = float.Parse(memberDetails["CMEM_TREAVELWALLET"].ToString());
            }

            model.SelectedCountry = memberDetails["CCOUNTRY_CODE"].ToString();

            #region Transaction type
            string add = Resources.OneForAll.OneForAll.btnAdd;
            string deduct = Resources.OneForAll.OneForAll.cntranDeduct;
            List<string> typeList = new List<string>();
            typeList.Add(add);
            typeList.Add(deduct);

            model.Transaction = from c in typeList
                                select new SelectListItem
                                {
                                    Selected = false,
                                    Text = c.ToString(),
                                    Value = (c.ToString() == add) ? "TOPUP" : "DED" //this is for cashname
                                };

            #endregion

            #region PaymentMode
            List<string> modelist = new List<string>();
            var ds = MemberDB.GetAllPaymentMode(out ok, out msg);
            foreach (DataTable table in ds.Tables)
            {
                foreach (DataRow dr in table.Rows)
                {
                    string mode = dr["CPAYMD_TYPE"].ToString();
                    modelist.Add(mode);
                }
            }

            model.paymentmode = from c in modelist
                                select new SelectListItem
                                {
                                    Selected = false,
                                    Text = c.ToString(),
                                    Value = (c.ToString())
                                };
            #endregion

            return PartialView("WalletAdjustment", model);
        }

        [HttpPost]
        public JsonResult FindBank(string CountryCode)
        {
            string LanguageCode = Session["LanguageChosen"].ToString();

            var result = GetBankList(LanguageCode, CountryCode);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public static IEnumerable<SelectListItem> GetBankList(string LanguageCode, string CountryCode)
        {
            List<SelectListItem> list = new List<SelectListItem>();
            int ok = 0;
            string message = "";
            List<BankModel> banks = Misc.GetAllBankByCountry(LanguageCode, CountryCode, ref ok, ref message);

            var result = from c in banks
                         select new SelectListItem
                         {
                             Selected = false,
                             Text = c.BankName,
                             Value = c.BankCode
                         };
            return result.OrderBy(m => m.Value).ToList();
        }

        [HttpPost]
        public ActionResult WalletAdjustmentMethod(WalletAdjustmentModel walletMem)
        {
            try
            {
                if (Session["Admin"] == null || Session["Admin"].ToString() == "")
                {
                    return RedirectToAction("AdminLogin", "Admin", new {  });
                }

                int ok = 0;
                string msg = "";
                string abc = walletMem.selectedmode;
                if (walletMem.Remark == "")
                {
                    walletMem.Remark = "";
                }
                if (walletMem.TransactionWallet == 0)
                {
                    Response.Write("Please key in amount to be adjusted");
                    return Json(string.Empty, JsonRequestBehavior.AllowGet);
                }
                if (walletMem.SelectedTransaction == "DED")
                {
                    walletMem.TransactionWallet = 0 - walletMem.TransactionWallet;
                }

                if (walletMem.Type == ProjectStaticString.RegisterwalletTopUp)
                {
                    AdminWalletDB.WalletAdjustment("SP_WalletRegisterAdjustment", walletMem.Username, walletMem.TransactionWallet, walletMem.SelectedTransaction, walletMem.Remark, walletMem.SelectedCountry, walletMem.Type, Session["Admin"].ToString(), walletMem.selectedmode, out ok, out msg);
                }
                else if (walletMem.Type == ProjectStaticString.CashwalletTopUp)
                {
                    AdminWalletDB.WalletAdjustment("SP_WalletCashAdjustment", walletMem.Username, walletMem.TransactionWallet, walletMem.SelectedTransaction, walletMem.Remark, walletMem.SelectedCountry, walletMem.Type, Session["Admin"].ToString(), walletMem.selectedmode, out ok, out msg);
                }
                else if (walletMem.Type == ProjectStaticString.GoldPointTopUp)
                {
                    AdminWalletDB.WalletAdjustment("SP_WalletGoldPointAdjustment", walletMem.Username, walletMem.TransactionWallet, walletMem.SelectedTransaction, walletMem.Remark, walletMem.SelectedCountry, walletMem.Type, Session["Admin"].ToString(), walletMem.selectedmode, out ok, out msg);
                }
                else if (walletMem.Type == ProjectStaticString.MultiPointTopUp)
                {

BVA/BVA/Views/AdminWallet/WalletAdjustment.cshtml
@using ECFBase.Models
@using resShared = ECFBase.Resources.OneForAll.OneForAll;
@using resAdminHome = ECFBase.Resources.OneForAll.OneForAll;
@model WalletAdjustmentModel
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script type="text/javascript">

    $("#btnTopUp").click(function (evt) {
        
        //$("#divLoader").show();
        if (confirm("@resShared.warningConfirmToTopUpWallet")) {
            $.validator.unobtrusive.parse($('#topupMem'));
            $('#Loading').show();
            if ($('#topupMem').valid()) {
                $.ajax({
                    type: "POST",
                    url: "/AdminWallet/WalletAdjustmentMethod",
                    data: $("#topupMem").serialize(),
                    success: function (data) {
                        $("#divLoader").hide();  
                        alert("@resAdminHome.msgSaveSuccessfully");
                        $("#main-content").html(data);
                       $('#Loading').hide();
                    },
                    error: function (xhr, status, error) {
                        var errorM = xhr.responseText;
                        errorM = errorM.replace('""', '');
                        alert(errorM);
                       $('#Loading').hide();
                        $("#btnTopUp").attr("disabled", false);
                    }
                });
            } return false;
        } else {
           
        }

        
    });

    $('#SelectedCountry').change(function () {
        $('#Loading').show();
        //Clear and refresh Province dropdown
        $.ajax({
            url: "/AdminWallet/FindBank",
            dataType: "json",
            type: "POST",
            delay: 0,
            data: { CountryCode: $(document.getElementById("SelectedCountry")).val() },
            success: function (data) {
                var selectList = $(document.getElementById("SelectedBank"));
                selectList.empty();
                $.each(data, function (index, optionData) {
                    var option = $('<option>').text(optionData.Text).val(optionData.Value);
                    selectList.append(option);
                    $('#Loading').hide();
                });
            }
        });
    });

</script>


<div class="container-fluid">
    @{ Html.EnableClientValidation(true); }
    @using (Html.BeginForm("TopUp", "AdminWallet", FormMethod.Post, new { enctype = "multipart/form-data", name = "topupMem", id = "topupMem" })) //this id very important to do HttpPost
    {
        //display Model's errors
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => @Model.Type)
        @Html.HiddenFor(model => @Model.SelectedCountry)
        @Html.HiddenFor(model => @Model.Username)
        <div class="row">
            <div class="col-lg-12">
                 <h2>@Model.TypeResource</h2>
                    <ol class="breadcrumb default square rsaquo sm no-border ">
					    <li><a href="javascript:;" id="Home"><i class="fa fa-home"></i></a></li>
                        <li><a href="#">@resAdminHome.lblWallet</a></li>
                        <li><a href="#">@resAdminHome.lblUtility</a></li>
                        <li><a href="#" onclick="dummy(0);return false;">@Model.TypeResource</a></li>
                    </ol>
                <h1 class="page-sub-header"></h1>
            </div>
        </div>
        <div class="row" align="center">
            <div style="text-align: left; float:none" class="col-lg-5 col-md-8 col-sm-12">
                <div class="form-group">
                    <strong>@resShared.lblUsername</strong>
                    @Html.TextBoxFor(model => model.Username, new { @class = "form-control", disabled = "disabled" })
                </div>
            </div>
        </div>
        <div class="row" align="center">
            <div style="text-align: left; float:none" class="col-lg-5 col-md-8 col-sm-12">
                <div class="form-group">
                    <strong>@Model.WalletBalanceTypeResource</strong>
                    @Html.TextBoxFor(model => model.CurrentWallet, "{0:#,###0.00}", new { @class = "form-control", disabled = "disabled" })
                </div>
            </div>
        </div>
        <div class="row" align="center">
            <div style="text-align: left; float:none" class="col-lg-5 col-md-8 col-sm-12">
                <div class="form-group">
                    <strong>@resAdminHome.lblNickname2</strong>
                    @Html.TextBoxFor(model => model.Nickname, new { @class = "form-control", disabled = "disabled" })
                </div>
            </div>
        </div>
        <div class="row" align="center">
            <div style="text-align: left; float:none" class="col-lg-5 col-md-8 col-sm-12">
                <div class="form-group">
                    <strong>@resAdminHome.lblAction <span style="color: Red">*</span></strong>
                    @Html.DropDownListFor(m => m.SelectedTransaction, @Model.Transaction, new { @class = "form-control" })
                    <div style="margin-left: 0px;">
                        @Html.ValidationMessageFor(m => Model.SelectedTransaction)
                    </div>
                </div>
            </div>
        </div>
        <div class="row" align="center">
            <div style="text-align: left; float:none" class="col-lg-5 col-md-8 col-sm-12">
                <div class="form-group">
                    <strong>@resAdminHome.lblAmtUSD<span style="color: Red">*</span></strong>
                    @Html.TextBoxFor(m => @Model.TransactionWallet, new { @class = "form-control" })
                    <div style="margin-left: 0px;">
                        @Html.ValidationMessageFor(m => Model.TransactionWallet)
                    </div>
                </div>
            </div>
        </div>
    
        <div class="row" align="center">
            <div style="text-align: left; float:none" class="col-lg-5 col-md-8 col-sm-12">
                <div class="form-group">
                    <strong>@resAdminHome.lblPaymentmode <span style="color: Red">*</span></strong>
                    @Html.DropDownListFor(m => m.selectedmode, @Model.paymentmode, new { @class = "form-control" })
                    <div style="margin-left: 0px;">
                        @Html.ValidationMessageFor(m => Model.selectedmode)
                    </div>
                </div>
            </div>
        </div>
        
        <div class="row" align="center">
            <div style="text-align: left; float:none" class="col-lg-5 col-md-8 col-sm-12">
                <div class="form-group">
                    <strong>@resAdminHome.lblRemark</strong> @*<span style="color: Red">*</span>*@
                    @Html.TextAreaFor(m => @Model.Remark, new { maxlength = "100", @class = "form-control", placeholder = "Max 100 characters" })
                    <div style="margin-left: 0px;">
                        @Html.ValidationMessageFor(m => Model.Remark)
                    </div>
                </div>
            </div>
        </div> 
        
            <div class="row" align="center">
                <div style="max-width: 600px;">
                    <div class="form-group">
                        <button id="btnTopUp" type="button" class="btn btn-sm btn-success" style="width:100px">@resAdminHome.lblConfirm</button>
                    </div>
                </div>
            </div>
       
    }
   
</div>

BVA/BVA/Views/AdminWallet/WithdrawalCashLog.cshtml
@using resShared = ECFBase.Resources.OneForAll.OneForAll;
@using ECFBase.Models
@model PaginationWalletLogModel

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script type="text/javascript">

    $(document).ready(function () {

        function stopRKey(evt) {
            var evt = (evt) ? evt : ((event) ? event : null);
            var node = (evt.target) ? evt.target : ((evt.srcElement) ? evt.srcElement : null);
            if ((evt.keyCode == 13) && (node.type == "text")) { return false; }
        }
        document.onkeypress = stopRKey;


    });


    $("#btnPage").click(function (evt) {
        $('#Loading').show();
            var e = document.getElementById("page")
            var page = e.options[e.selectedIndex].value;

            $.ajax({
                type: "POST",
                url: "/AdminWallet/WithdrawalCashLog",
                data: { selectedPage: page },
                success: function (data) {
                    $("#main-content").html(data);
                   $('#Loading').hide();
                },
                error: function (xhr, status, error) {
                    var errorM = xhr.responseText;
                    errorM = errorM.replace('""', '');
                    alert(errorM);
                   $('#Loading').hide();
                }
            });
        });

    $("#WithdrawalCashLog").click(function (evt) {
           $('#Loading').show();

            var e = document.getElementById("page")
            if (e == null) {
                var page = 1;
            }
            else {
                var page = e.options[e.selectedIndex].value;
            }
            $.ajax({
                type: "POST",
                url: "/AdminWallet/WithdrawalCashLog",
                data: { selectedPage: page, Username: $('#searchName').val() },
                success: function (data) {
                    $("#main-content").html(data);
                   $('#Loading').hide();
                },
                error: function (xhr, status, error) {
                    var errorM = xhr.responseText;
                    errorM = errorM.replace('""', '');
                    alert(errorM);
                   $('#Loading').hide();
                }
            });
        });    
</script>

<div class="row">
    <div class="col-lg-12">
         <h2 style="padding-left:10px;">@resShared.mnuCPWithdrawalLog</h2>
    <!-- Begin breadcrumb -->
				<ol class="breadcrumb default square rsaquo sm no-border " style="margin:10px;">
					<li><a href="javascript:;" id="Home"><i class="fa fa-home"></i></a></li>
					<li><a href="#">@resShared.mnuWallet</a></li>
					<li><a href="#">@resShared.mnuReports</a></li>
					<li class="active"><a href="#" onclick="dummy(0);return false;">@resShared.mnuCPWithdrawalLog</a></li>
				</ol>
		<!-- End breadcrumb -->
        <h1 class="page-sub-header"></h1>
    </div>
</div>

@{ Html.EnableClientValidation(true); }
@using (Html.BeginForm("WithdrawBonus", "AdminWallet", FormMethod.Post, new { name = "MemberDiv", id = "MemberDiv" })) //this id very important to do HttpPost
{
    //display Model's errors
    @Html.ValidationSummary(true)
    <div>
    <div class="grid" style="margin-left: 5px;" id="grid">
     <div class="grid">
         <div class="row">
             <div class="col-xs-12" style="padding-bottom:10px; padding-left:0">
                 <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4" style="text-align:right">
                     @resShared.lblUsername:
                 </div>
                 <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4" style="padding:0">
                     <input type="text" class="form-control" id="searchName" />
                 </div>
                 <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                     <button id="btnSearchByName" type="button" class="btn btn-sm btn-success" style="width:100px">@resShared.btnSearch</button>
                 </div>
             </div>
         </div>
      @*<table width="100%" class="test">
        <tr>
            <td style="text-align:right">
                <label>@resShared.lblUsername:</label>
             </td>
             <td style="padding-left:10px; width:200px">
                <input type="text" class="form-control" id="searchName" />
            </td>
            <td style="padding-left:10px">
                <button id="btnSearchByName" type="button" class="btn btn-sm btn-success" style="width:100px">@resShared.btnSearch</button>
            </td>
         </tr>
    </table>*@
    <br />
    <div class="table-responsive">
        <table id="tablestyle" class="table table-bordered table-hover table-striped" >
            <thead>
                <tr style="background-color: #414558;">
                    <th style="text-align:center;color:White">
                        @resShared.lblNumber
                    </th>
                    <th style="text-align:center;color:White">
                        @resShared.lblUsername
                    </th>
                    <th style="text-align:center;color:White">
                        @resShared.lblWithdrawAmt
                    </th>
                    <th style="text-align:center;color:White">
                        @resShared.lblCountry
                    </th>
                    <th style="text-align:center;color:White">
                        @resShared.lblBank
                    </th>

                    <th style="text-align:center;color:White">
                        Branch Name
                    </th>
                    <th style="text-align:center;color:White">
                        Branch Address
                    </th>

                    <th style="text-align:center;color:White">
                        Branch Swift Code
                    </th>
                    <th style="text-align:center;color:White">
                        @resShared.lblBankAccountNo
                    </th>
                    <th style="text-align:center;color:White">
                        Mailing Address
                    </th>
                    <th style="text-align:center;color:White">
                        @resShared.lblFullname
                    </th>
                    <th style="text-align:center;color:White">
                        @resShared.lblApplyDate
                    </th>
                    <th style="text-align:center;color:White">
                        @resShared.lblApprovedDate
                    </th>
                    <th style="text-align:center;color:White">
                        @resShared.lblStatus
                    </th>
                </tr>
                </thead>
                <tbody>
                    @if (Model.WalletLogList.Count == 0)
                    {
                        <tr style="height: 25px; border-top: 2px solid white;">
                            <td style="padding: 5px;" colspan="10">
                                @resShared.lblNoRecFound
                            </td>
                        </tr>
                    }
                    @foreach (var item in Model.WalletLogList)
                    {
                        <tr style="height: 25px; border-top: 2px solid white;">
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.No)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.Username)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.CashOut)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.CountryName)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.Bank)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.BranchName)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.BranchAdd)
                            </td>

                            <td align="center">
                                @Html.DisplayFor(modelItem => item.BranchSwiftCode)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.AccNo)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.Address)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.FullName)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.CreatedDate)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.TranState)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.status)
                            </td>

                        </tr>
                    }                 
                </tbody>
            </table>
        </div>
            @if (Model.WalletLogList.Count > 0)
            {
                <table  width="auto" style="text-align:right; margin-right:0px; margin-left:auto;">
                   <tr>
                        <td style="text-align: right">
                            <div class="BtnClass" style="float: right;">
                                @Html.DropDownList("page", @Model.Pages, new { @class = "form-control", style = "width:80px;" })
                        </div>
                        </td>
                        <td style="text-align: right">
                               <button id="btnPage" type="button" class="btn btn-sm btn-success" style="width:100px">@resShared.btnView</button>
                        </td>
                    </tr>
                </table>
            }
        </div>
    </div>
</div>
}
          