BVA/BVA/Controllers/Admin/AdminStockController.cs
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Script.Serialization;
using ECFBase.Models;
using ECFBase.Components;
using System.Data;
using System.Web.Services;
using ECFBase.Resources;
using System.Collections.Generic;
using ECFBase.Helpers;

namespace ECFBase.Controllers.Admin
{
    public class AdminStockController : Controller
    {
        #region Mobile
        public ActionResult AddMobileList(int selectedPage = 1, string searchMemberList = "")
        {
            if (Session["Admin"] == null || Session["Admin"].ToString() == "")
            {
                return RedirectToAction("AdminLogin", "Admin", new {  });
            }

            int status = 0;
            string message = string.Empty;
            int pages = 0;
            string languageCode = Session["LanguageChosen"].ToString();

            PaginationMobileAgent model = new PaginationMobileAgent();
            DataSet dsAgents = MemberDB.GetAllMobileAgents(searchMemberList, selectedPage, languageCode, out pages, out status, out message);

            selectedPage = ConstructPageList(selectedPage, pages, model);

            RetrieveMobilePosition(model);

            foreach (DataRow dr in dsAgents.Tables[0].Rows)
            {
                var mobileAgent = new MobileAgent();
                mobileAgent.Number = dr["rownumber"].ToString();
                mobileAgent.AgentID = dr["CUSR_USERNAME"].ToString();
                mobileAgent.FullName = dr["CUSR_FULLNAME"].ToString();
                mobileAgent.Percentage = float.Parse(dr["CMEM_MOBILE_PERCENTAGE"].ToString()).ToString("n2");
                mobileAgent.JoinedDate = Convert.ToDateTime(dr["CMEM_CREATEDON"]).ToString("dd/MM/yyyy");
                mobileAgent.Country = dr["CMULTILANGCOUNTRY_NAME"].ToString();
                mobileAgent.AdminApproved = dr["CMEM_APPROVEBY"].ToString();
                //mobileAgent.DateApproved = Convert.ToDateTime(dr["CMEM_UPDATEDON"]).ToShortDateString();
                mobileAgent.DateApproved = Convert.ToDateTime(dr["CMEM_UPDATEDON"]).ToString("dd/MM/yyyy");
                model.MobileList.Add(mobileAgent);
            }

            return PartialView("AddMobile", model);
        }

        private static void RetrieveMobilePosition(PaginationMobileAgent model)
        {
            List<SelectListItem> positions = new List<SelectListItem>();

            //SelectListItem fcPos = new SelectListItem();
            //fcPos.Text = Resources.OneForAll.OneForAll.lblMobile;
            //fcPos.Value = "1";
            //positions.Add(fcPos);

            SelectListItem fcPos = new SelectListItem();
            fcPos.Text = ECFBase.Resources.OneForAll.OneForAll.lblStockist;
            fcPos.Value = "2";
            positions.Add(fcPos);

            fcPos = new SelectListItem();
            fcPos.Text = Resources.OneForAll.OneForAll.lblRegional;
            fcPos.Value = "3";
            positions.Add(fcPos);

            fcPos = new SelectListItem();
            fcPos.Text = Resources.OneForAll.OneForAll.lblCountry;
            fcPos.Value = "4";
            positions.Add(fcPos);

            model.Positions = positions;
        }

        public ActionResult DisqualifyMobile(string username)
        {
            if (Session["Admin"] == null || Session["Admin"].ToString() == "")
            {
                return RedirectToAction("AdminLogin", "Admin", new {  });
            }

            MemberDB.DisqualifiedMobile(username, Session["Admin"].ToString());

            return AddMobileList(1, "");
        }

        public ActionResult AppointMobileUser(string username, string percentage)
        {
            if (Session["Admin"] == null || Session["Admin"].ToString() == "")
            {
                return RedirectToAction("AdminLogin", "Admin", new {  });
            }

            int ok = 0;
            string msg = "";

            var ds = MemberDB.GetMemberByUsername(username, out ok , out msg);

            if (ds.Tables[0].Rows.Count == 0)
            {
                Response.Write("Invalid Username");
                return Json(string.Empty, JsonRequestBehavior.AllowGet);
            }

            
            MemberDB.AppointMobileUser(username, Session["Admin"].ToString(), percentage);
            return AddMobileList();
        }

        [HttpPost]
        public JsonResult findUserName(string memberID)
        {
            int ok = 0;
            string msg = string.Empty;

            if (string.IsNullOrEmpty(memberID))
            {
                return Json(string.Empty, JsonRequestBehavior.AllowGet);
            }

            var dsMember = MemberDB.GetMemberByUsername(memberID, out ok, out msg);

            if (dsMember.Tables[0].Rows.Count == 0)
            {
                Response.Write(Resources.OneForAll.OneForAll.warningInvalidUsername2);
                return Json(string.Empty, JsonRequestBehavior.AllowGet);
            }


            var result = dsMember.Tables[0].Rows[0]["CUSR_FULLNAME"].ToString();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult RequestTopUp()
        {
            try
            {
                if (Session["Admin"] == null || Session["Admin"].ToString() == "")
                {
                    return RedirectToAction("AdminLogin", "Admin", new {  });
                }
                
                PaginationMobileAgent model = new PaginationMobileAgent();

                
                DataSet dsWallet = AdminGeneralDB.GetAllPendingRequest();

                string previous = string.Empty;
                foreach (DataRow dr in dsWallet.Tables[0].Rows)
                {
                    MobileRequestList Request = new MobileRequestList();
                    Request.PinID = dr["CTUR_ID"].ToString();
                    //Request.Date = dr["CTUR_CREATEDON"].ToString();
                    Request.Date = Convert.ToDateTime(dr["CTUR_CREATEDON"]).ToString("dd/MM/yyyy");
                    Request.ReferenceOrder = dr["CTUR_REFFERALID"].ToString();
                    Request.MemberID = dr["CUSR_USERNAME"].ToString();
                    Request.FullName = dr["CTUR_FULLNAME"].ToString();
                    Request.TopUpFor = dr["CTUR_FROM"].ToString();
                    Request.Currency = dr["CTUR_CURRENCY"].ToString();
                    Request.LocalAmount = float.Parse(dr["CTUR_LOCAL_AMOUNT"].ToString()).ToString("n2");
                    Request.Amount = float.Parse(dr["CTUR_AMOUNT"].ToString()).ToString("n2");
                    Request.Remark = dr["CTUR_REMARK"].ToString();
                    Request.AdminRemark = dr["CTUR_ADMIN_REMARK"].ToString();
                    Request.VerifyBy = dr["CTUR_APPROVEBY"].ToString();
                    
                    Request.ApprovedBy = dr["CTUR_GENERATEBY"].ToString();
                    Request.Province = dr["CTUR_PROVINCE"].ToString();
                    Request.BranchName = dr["CTUR_PROVINCE"].ToString();


                    if (dr["CTUR_STATUS"].ToString() == "Pending")
                    {
                        Request.VerifyOn = "";
                        Request.ApprovedOn = "";
                    }
                    else
                    {
                        if (dr["CTUR_STATUS"].ToString() == "Approve")
                        {
                            //Request.VerifyOn = dr["CTUR_APPROVETIME"].ToString();
                            Request.VerifyOn = Convert.ToDateTime(dr["CTUR_APPROVETIME"]).ToString("dd/MM/yyyy");
                            Request.ApprovedOn = "";
                        }
                        else
                        {
                            //Request.VerifyOn = dr["CTUR_APPROVETIME"].ToString();
                            //Request.ApprovedOn = dr["CTUR_GENERATEON"].ToString();
                            Request.VerifyOn = Convert.ToDateTime(dr["CTUR_APPROVETIME"]).ToString("dd/MM/yyyy");
                            Request.ApprovedOn = Convert.ToDateTime(dr["CTUR_GENERATEON"]).ToString("dd/MM/yyyy");
                        }
                    }

                    Request.Status = dr["CTUR_STATUS"].ToString();

                    model.MobileTopUpList.Add(Request);
                }
                
                return PartialView("RequestTopUp", model);
            }
            catch (Exception e)
            {
                Response.Write(e.Message);
                return Json(string.Empty, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult VeryfyRequestTopUp(string ID)
        {
            int ok = 0;
            string msg = string.Empty;

            PaginationMobileAgent model = new PaginationMobileAgent();
            

            DataSet dr = AdminGeneralDB.GetRequestTopUpByID(Convert.ToInt32(ID));
            model.PinID = dr.Tables[0].Rows[0]["CTUR_ID"].ToString();
            //model.Date = dr.Tables[0].Rows[0]["CTUR_CREATEDON"].ToString();
            model.Date = Convert.ToDateTime(dr.Tables[0].Rows[0]["CTUR_CREATEDON"]).ToString("dd/MM/yyyy");
            model.Username = dr.Tables[0].Rows[0]["CUSR_USERNAME"].ToString();
            var ds = MemberDB.GetMemberByUsername(model.Username , out ok, out msg);
            model.Name = ds.Tables[0].Rows[0]["CUSR_FULLNAME"].ToString();
            model.USDAmount = float.Parse(dr.Tables[0].Rows[0]["CTUR_AMOUNT"].ToString()).ToString("n2");
            model.LocalAmount = float.Parse(dr.Tables[0].Rows[0]["CTUR_LOCAL_AMOUNT"].ToString()).ToString("n2");
            model.Country = Misc.GetCountryNameByCountryCode(ds.Tables[0].Rows[0]["CCOUNTRY_CODE"].ToString());
            model.Status = dr.Tables[0].Rows[0]["CTUR_STATUS"].ToString();            
            int extensionIndex = dr.Tables[0].Rows[0]["CTUR_IMAGE"].ToString().LastIndexOf('\\');

BVA/BVA/Views/AdminStock/GenerateTopUpDataByID.cshtml
@using resShared = ECFBase.Resources.OneForAll.OneForAll; 
@using ECFBase.Models
@model PaginationMobileAgent



<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        &times;
    </button>
    <h4 class="modal-title">
        <center>
            @resShared.mnuGenerateTopUp
        </center>
    </h4>
</div>
<div id="ModalBody" class="modal-body">
    @Html.HiddenFor(M => M.PinID, new { id = "ID" })
    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <strong>@resShared.lblRequestDate<span style="color: Red">*</span></strong>
                @Html.TextBoxFor(m => @Model.Date, new { @disabled = "disabled", @class = "form-control" })
            </div>
        </div>
    </div>

    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <strong>@resShared.lblUsername<span style="color: Red">*</span></strong>
                @Html.TextBoxFor(m => @Model.Username, new { @disabled = "disabled", @class = "form-control" })
            </div>
        </div>
    </div>

    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <strong>@resShared.lblName<span style="color: Red">*</span></strong>
                @Html.TextBoxFor(m => @Model.Name, new { @disabled = "disabled", @class = "form-control" })
            </div>
        </div>
    </div>

    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <strong>@resShared.lblCountry<span style="color: Red">*</span></strong>
                @Html.TextBoxFor(m => @Model.Country, new { @disabled = "disabled", @class = "form-control" })
            </div>
        </div>
    </div>

    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <strong>@resShared.lblAmtUSD<span style="color: Red">*</span></strong>
                @Html.TextBoxFor(m => @Model.USDAmount, new { @disabled = "disabled", @id = "USDAmount", @class = "form-control" })
            </div>
        </div>
    </div>

    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <strong>@resShared.lblLocalAmount<span style="color: Red">*</span></strong>
                @Html.TextBoxFor(m => @Model.LocalAmount, new { @id = "RMAmount", @disabled = "disabled", @class = "form-control" })
            </div>
        </div>
    </div>

    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <strong>@resShared.lblRemark<span style="color: Red">*</span></strong>
                @Html.TextBoxFor(m => @Model.Remark, new { @class = "form-control", @disabled = "disabled" })
            </div>
        </div>
    </div>

    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <strong>@resShared.lblStatus<span style="color: Red">*</span></strong>
                @Html.TextBoxFor(m => @Model.Status, new { @class = "form-control", @disabled = "disabled" })
            </div>
        </div>
    </div>

    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <strong>@resShared.lblApprovedBy<span style="color: Red">*</span></strong>
                @Html.TextBoxFor(m => @Model.ApproveBy, new { @class = "form-control", @disabled = "disabled" })
            </div>
        </div>
    </div>

    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <strong>@resShared.lblApprovedOn<span style="color: Red">*</span></strong>
                @Html.TextBoxFor(m => @Model.ApproveOn, new { @class = "form-control", @disabled = "disabled" })
            </div>
        </div>
    </div>

    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <strong>@resShared.lblPaymentMethod<span style="color: Red">*</span></strong>
                @Html.TextBoxFor(m => @Model.PaymentMethod, new { @class = "form-control", @disabled = "disabled" })
            </div>
        </div>
    </div>

    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <strong>@resShared.lblImage<span style="color: Red">*</span></strong>
            </div>
        </div>
    </div>
    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <a href="@Html.DisplayFor(m => m.ImagePath)" target="_blank">
                    <img alt="" height="400" width="400" onerror="onError(this)" src="@Html.DisplayFor(m => m.ImagePath, new { @class = "form-control" })" />
                </a>
            </div>
        </div>
    </div>
</div>

BVA/BVA/Views/AdminStock/RequestTopUpDataByID.cshtml
@using resMembersReports = ECFBase.Resources.OneForAll.OneForAll;
@using resShared = ECFBase.Resources.OneForAll.OneForAll;
@using resMembersShopCenter = ECFBase.Resources.OneForAll.OneForAll;
@using ECFBase.Models
@model PaginationMobileAgent



<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        &times;
    </button>
    <h4 class="modal-title">
        <center>
            @resMembersReports.lblPaymentVerify
        </center>
    </h4>
</div>
<div id="ModalBody" class="modal-body">
    @Html.HiddenFor(M => M.PinID, new { id = "ID" })
    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <strong>@resMembersReports.lblRequestDate<span style="color: Red">*</span></strong>
                @Html.TextBoxFor(m => @Model.Date, new { @disabled = "disabled", @class = "form-control" })
            </div>
        </div>
    </div>

    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <strong>@resMembersReports.lblUsername<span style="color: Red">*</span></strong>
                @Html.TextBoxFor(m => @Model.Username, new { @disabled = "disabled", @class = "form-control" })
            </div>
        </div>
    </div>

    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <strong>@resMembersReports.lblName<span style="color: Red">*</span></strong>
                @Html.TextBoxFor(m => @Model.Name, new { @disabled = "disabled", @class = "form-control" })
            </div>
        </div>
    </div>

    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <strong>@resMembersReports.lblCountry<span style="color: Red">*</span></strong>
                @Html.TextBoxFor(m => @Model.Country, new { @disabled = "disabled", @class = "form-control" })
            </div>
        </div>
    </div>

    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <strong>@resMembersReports.lblAmountUSD<span style="color: Red">*</span></strong>
                @Html.TextBoxFor(m => @Model.USDAmount, new { @disabled = "disabled", @id = "USDAmount", @class = "form-control" })
            </div>
        </div>
    </div>

    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <strong>@resMembersReports.lblLocalAmount<span style="color: Red">*</span></strong>
                @Html.TextBoxFor(m => @Model.LocalAmount, new { @id = "RMAmount", @disabled = "disabled", @class = "form-control" })
            </div>
        </div>
    </div>
        
    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <strong>@resMembersReports.lblRemark<span style="color: Red">*</span></strong>
                @Html.TextBoxFor(m => @Model.Remark, new { @class = "form-control", @disabled = "disabled" })
            </div>
        </div>
    </div>

    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <strong>@resMembersReports.lblStatus<span style="color: Red">*</span></strong>
                @Html.TextBoxFor(m => @Model.Status, new { @class = "form-control", @disabled = "disabled" })
            </div>
        </div>
    </div>

    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <strong>@resMembersReports.lblPaymentMethod<span style="color: Red">*</span></strong>
                @Html.TextBoxFor(m => @Model.PaymentMethod, new { @class = "form-control", @disabled = "disabled" })
            </div>
        </div>
    </div>

    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <strong>@resMembersReports.lblAdminRemark<span style="color: Red">*</span></strong>
                @Html.TextBoxFor(m => @Model.AdminRemark, new { @class = "form-control", id = "AdminRemark" })
            </div>
        </div>
    </div>

    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <strong>@resMembersReports.lblImage<span style="color: Red">*</span></strong>
            </div>
        </div>
    </div>
    <div class="row" align="center">
        <div style="max-width: 400px; text-align: left">
            <div class="form-group">
                <a href="@Html.DisplayFor(m => m.ImagePath)" target="_blank">
                    <img alt="" height="400" width="400" onerror="onError(this)" src="@Html.DisplayFor(m => m.ImagePath, new { @class = "form-control" })" />
                </a>
            </div>
        </div>
    </div>
</div>

BVA/BVA/Views/AdminStock/RequestTopUpHistory.cshtml
@using ECFBase.Models
@model PaginationMobileAgent
@using resShared = ECFBase.Resources.OneForAll.OneForAll;
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script type="text/javascript">

    $("#btnPage").click(function (evt) {
        $('#Loading').show();
        var e = document.getElementById("page")
        var page = e.options[e.selectedIndex].value;
        $.ajax({
            type: "POST",
            url: "/AdminStock/RequestTopUpHistory",
            data: { selectedPage: page },
            success: function (data) {
                $("#main-content").html(data);
                $('#Loading').hide();
            },
            error: function (xhr, status, error) {
                var errorM = xhr.responseText;
                errorM = errorM.replace('""', '');
                alert(errorM);
                $('#Loading').hide();
            }
        });
    });


</script>
<div>
    <div class="row">
        <div class="col-lg-12">
            <h2 style="padding-left:10px;">@resShared.lblTopUpReqHis</h2>
            <!-- Begin breadcrumb -->
            <ol class="breadcrumb default square rsaquo sm no-border " style="margin:10px;">
                <li><a href="javascript:;" id="Home"><i class="fa fa-home"></i></a></li>
                <li><a href="#">@resShared.lblMobile</a></li>
                <li class="active"><a href="#" onclick="dummy(0);return false;">@resShared.lblTopUpReqHis</a></li>
            </ol>
            @*<ol class="breadcrumb">
                <li><i class="fa fa-dashboard"></i><a href="">@resShared.lblTopUpReqHis</a> </li>
            </ol>*@
            <h1 class="page-sub-header"></h1>
        </div>
    </div>
    <div class="table-responsive">
        <table id="tablestyle" class="table table-bordered table-hover table-striped">
            <thead>
                <tr style="background-color: #080808;">
                    <th style="text-align: center; color: White">
                        @resShared.lblDate
                    </th>
                    <th style="text-align: center; color: White">
                        @resShared.lblReference
                    </th>
                    <th style="text-align: center; color: White">
                        @resShared.lblStatus
                    </th>
                    <th style="text-align: center; color: White">
                        @resShared.lblUsername
                    </th>
                    <th style="text-align: center; color: White">
                        @resShared.lblFullname
                    </th>
                    <th style="text-align: center; color: White">
                        @resShared.lblTopUpFor
                    </th>
                    <th style="text-align: center; color: White">
                        @resShared.mnuCurrency
                    </th>
                    <th style="text-align: center; color: White">
                        @resShared.lblLocalAmount
                    </th>
                    <th style="text-align: center; color: White">
                        @resShared.lblAmountUSD
                    </th>           
                    <th style="text-align: center; color: White">
                        @resShared.lblApprovedBy
                    </th>
                    <th style="text-align: center; color: White">
                        @resShared.lblApprovedDate
                    </th>
                    <th style="text-align: center; color: White">
                        @resShared.lblAction
                    </th>
                    <th style="text-align: center; color: White">
                        @resShared.lblVerifiedBy
                    </th>
                    <th style="text-align: center; color: White">
                        @resShared.lblVerifiedOn
                    </th>
                </tr>
                @if (Model.MobileTopUpList.Count == 0)
                {
                    <tr style="height: 25px; border-top: 2px solid white;">
                        <td style="padding: 5px;" colspan="10">
                            @resShared.lblNoRecFound
                        </td>
                    </tr>
                }
            </thead>
            <tbody>
                @if (Model.MobileTopUpList.Count != 0)
                {
                    foreach (var item in Model.MobileTopUpList)
                    {
                        <tr>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.Date, "{0:dd/MM/yyyy}")
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.ReferenceOrder)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.Status)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.MemberID)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.FullName)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.TopUpFor)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.Currency)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.LocalAmount)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.Amount)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.GeneratedBy)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.GeneratedOn, "{0:dd/MM/yyyy}")
                            </td>
                            <td>
                                @if (string.IsNullOrEmpty(@item.ImagePath))
                                {
                                }
                                else
                                {
                                    <a href="@Url.Action("DownloadPaymentSlip", "AdminStock", new { fileName = @item.ImagePath, refOrder = @item.ReferenceOrder })">
                                        <img src="/Images/Download.png" border="0" alt="" style="width: 40px; min-height: 40px;" />
                                    </a>
                                }
                                
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.AdminID)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.ProcessedDate)
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
    @if (Model.MobileTopUpList.Count > 0)
    {
        <table width="auto" style="text-align:right; margin-right:0px; margin-left:auto;">
            <tr>
                <td style="text-align: right">
                    <div class="BtnClass" style="float: right;">
                        @Html.DropDownList("page", @Model.Pages, new { @class = "form-control", style = "width:80px;" }) 
                    </div>
                </td>
                <td style="text-align: right">
                    <div class="BtnClass" style="float: right;"> 
                        <button id="btnPage" type="button" class="btn btn-sm btn-success" style="width: 100px">@resShared.btnView</button>
                    </div>
                </td>
            </tr>
        </table>
    }
</div>