BVA/BVA/Controllers/Member/MemberShopCenterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using ECFBase.Models;
using System.Data;
using ECFBase.Components;
using System.Text.RegularExpressions;
using System.IO;
using ECFBase.Helpers;
using ECFBase.ThirdParties;
using System.Net;
using System.Web.Services;
using System.Web.Script.Services;
using Newtonsoft.Json;
using System.Collections.Specialized;
using System.Globalization;

namespace ECFBase.Controllers.Member
{
    public class MemberShopCenterController : Controller
    {

        #region Old Sponsor Chart

        //[WebMethod]
        //[ScriptMethod(UseHttpGet = true)]

        //public ActionResult SearchSponsor(string Username)
        //{
        //    try { 
        //    if (Session["Username"] == null || Session["Username"].ToString() == "")
        //    {
        //         return RedirectToAction("MemberLogin", "Member" , new {ReloadPage = "Yes" , Expired = "Yes"});
        //    }

        //    if (Username == null || Username == "")
        //    {
        //        Username = Session["Username"].ToString();
        //    }


        //    var model = new MemberSponsorChartModel();

        //        int ok;
        //        string msg;

        //        DataSet dsNetworkTree = MemberShopCenterDB.GetSponsorChart(Username, out ok, out msg);

        //    if (dsNetworkTree.Tables[0].Rows.Count > 0)
        //    {
        //        model.FirstLevelMember = dsNetworkTree.Tables[0].Rows[0]["USERNAME"].ToString();
        //        model.FirstLevelLevel = dsNetworkTree.Tables[0].Rows[0]["LEVEL"].ToString();
        //        model.FirstLevelJoinedDate = dsNetworkTree.Tables[0].Rows[0]["DATE"].ToString();
        //        model.FirstLevelRanking = dsNetworkTree.Tables[0].Rows[0]["RANK"].ToString();
        //        model.FirstLevelIntro = dsNetworkTree.Tables[0].Rows[0]["INTRO"].ToString();
        //        model.FirstLevelFullname = dsNetworkTree.Tables[0].Rows[0]["FULLNAME"].ToString();

        //        foreach (DataRow dr in dsNetworkTree.Tables[0].Rows)
        //        {
        //            MemberList resultList = new MemberList();
        //            var info = GetMemberSponsorInfo(dr);
        //            resultList.Level = dr["LEVEL"].ToString();
        //            resultList.Member = dr["USERNAME"].ToString();
        //            resultList.Ranking = dr["RANK"].ToString();
        //            resultList.JoinedDate = dr["DATE"].ToString();
        //            resultList.FullName = dr["FULLNAME"].ToString();
        //            resultList.Intro = dr["INTRO"].ToString();

        //            model.resultList.Add(resultList);

        //        }

        //        ViewBag.MemberCount = 0;
        //    }
        //    else
        //    {
        //            Response.Write(Resources.OneForAll.OneForAll.warningPlsKeyInSearchID);
        //            return Json(string.Empty, JsonRequestBehavior.AllowGet);
        //    }

        //        return PartialView("SponsorChartTree", model);
        //    }
        //    catch (Exception e)
        //    {
        //        Response.Write(e.Message);
        //        return Json(string.Empty, JsonRequestBehavior.AllowGet);
        //    }
        //}

        //public ActionResult SponsorChartTree(string memberUsername, int? memberLevel)
        //{
        //    if (Session["Username"] == null || Session["Username"].ToString() == "")
        //    {
        //         return RedirectToAction("MemberLogin", "Member" , new {ReloadPage = "Yes" , Expired = "Yes"});
        //    }

        //    string username;
        //    if (memberUsername == null)
        //    {
        //        username = Session["Username"].ToString();
        //        ViewBag.MemberLevel = 1;
        //        ViewBag.NextLevel = 4;
        //        Session["PreviousView"] = null;
        //    }
        //    else
        //    {
        //        username = memberUsername;
        //        ViewBag.MemberLevel = memberLevel;
        //        ViewBag.NextLevel = memberLevel + 3;
        //    }

        //    //Store Previous username and level
        //    List<String> userNameList = new List<String>();
        //    if (Session["PreviousView"] == null)
        //    {
        //        userNameList.Add(username + ";" + ViewBag.MemberLevel);
        //        Session["PreviousView"] = userNameList;
        //    }
        //    else
        //    {
        //        userNameList = (List<string>)Session["PreviousView"];
        //        userNameList.Add(memberUsername + ";" + memberLevel);
        //        Session["PreviousView"] = userNameList;
        //    }

        //    var model = new MemberSponsorChartModel();

        //    int ok;
        //    string msg;
        //    DataSet dsNetworkTree = MemberShopCenterDB.GetSponsorChart(username, out ok, out msg);
        //    ViewBag.MemberCount = 0;

        //    var member = MemberDB.GetMemberByUsername(username, out ok, out msg);

        //    model.FirstLevelMember = dsNetworkTree.Tables[0].Rows[0]["USERNAME"].ToString();
        //    model.FirstLevelLevel = dsNetworkTree.Tables[0].Rows[0]["LEVEL"].ToString();
        //    model.FirstLevelJoinedDate = dsNetworkTree.Tables[0].Rows[0]["DATE"].ToString();
        //    model.FirstLevelRanking = Misc.GetMemberRanking(dsNetworkTree.Tables[0].Rows[0]["RANK"].ToString());
        //    //model.FirstLevelRanking = dsNetworkTree.Tables[0].Rows[0]["RANK"].ToString();
        //    model.FirstLevelIntro = dsNetworkTree.Tables[0].Rows[0]["INTRO"].ToString();
        //    model.FirstLevelFullname = dsNetworkTree.Tables[0].Rows[0]["FULLNAME"].ToString();
        //    model.FirstLevelRankIcon = member.Tables[0].Rows[0]["CRANKSET_ICON"].ToString();

        //    foreach (DataRow dr in dsNetworkTree.Tables[0].Rows)
        //    {
        //        MemberList resultList = new MemberList();
        //        var info = GetMemberSponsorInfo(dr);
        //        resultList.Level = dr["LEVEL"].ToString();
        //        resultList.Member = dr["USERNAME"].ToString();
        //        resultList.Ranking = Misc.GetMemberRanking(dr["RANK"].ToString());
        //        //resultList.Ranking = dr["RANK"].ToString();
        //        resultList.JoinedDate = dr["DATE"].ToString();
        //        resultList.FullName = dr["FULLNAME"].ToString();
        //        resultList.Intro = dr["INTRO"].ToString();
        //        resultList.RankIcon = dr["ICON"].ToString();

        //        model.resultList.Add(resultList);

        //    }

        //    DataSet logo = AdminGeneralDB.GetRankIcon();
        //    foreach (DataRow dr in logo.Tables[0].Rows)
        //    {
        //        var IFile = new ImageFile();
        //        IFile.FileName = dr["CRANKSET_ICON"].ToString();
        //        RankModel RankList = new RankModel();
        //        RankList.RankIconPath = dr["CRANKSET_ICON"].ToString();
        //        //RankList.RankIconName = dr["AMOUNT"].ToString();
        //        RankList.RankName = dr["CRANKSET_NAME"].ToString();
        //        ViewBag.Rank = logo.Tables[0].Rows[0]["CRANKSET_ICON"].ToString();

        //        model.RankList.Add(RankList);
        //    }

        //              return PartialView("SponsorChartTree", model);
        //}

        //private MemberSponsorChartModel GetMemberSponsorInfo(DataRow dr)
        //{
        //    var mntm = new MemberSponsorChartModel();

        //    mntm.Level = dr["LEVEL"].ToString();
        //    mntm.Member = dr["USERNAME"].ToString();
        //    mntm.Ranking = Misc.GetMemberRanking(dr["RANK"].ToString());
        //    mntm.JoinedDate = DateTime.Parse(dr["DATE"].ToString()).ToShortDateString();
        //    mntm.FullName = dr["FULLNAME"].ToString();
        //    mntm.Intro = dr["INTRO"].ToString();
        //    mntm.RankIcon = dr["ICON"].ToString();

        //    return mntm;
        //}
        #endregion

        #region SponsorChart

        [WebMethod]
        [ScriptMethod(UseHttpGet = true)]
        public ActionResult SearchSponsor(string Username)
        {
            try
            {
                if (Session["Username"] == null || Session["Username"].ToString() == "")
                {
                     return RedirectToAction("MemberLogin", "Member" , new {ReloadPage = "Yes" , Expired = "Yes"});
                }

                string Status = "";
                MemberDB.GetTime(out Status);

                if (Session["Admin"] == null)
                {
                    if (Status == "1")
                    {
                        return RedirectToAction("MemberLogin", "Member", new { ReloadPage = "Yes", Expired = "Yes" });
                    }

                }

                if (Username == null || Username == "")
                {
                    Username = Session["Username"].ToString();
                }

                var model = new MemberSponsorChartModel();

                int ok;
                string msg;
                DataSet dsNetworkTree = MemberShopCenterDB.GetSponsorChart(Username, out ok, out msg);

                if (dsNetworkTree.Tables[0].Rows.Count > 0)
                {
                    model.FirstLevelMember = dsNetworkTree.Tables[0].Rows[0]["USERNAME"].ToString();
                    model.FirstLevelLevel = dsNetworkTree.Tables[0].Rows[0]["LEVEL"].ToString();
                    //model.FirstLevelJoinedDate = dsNetworkTree.Tables[0].Rows[0]["DATE"].ToString();

                    var Date = dsNetworkTree.Tables[0].Rows[0]["DATE"].ToString();
                    model.FirstLevelJoinedDate = Convert.ToDateTime(Date).ToString("dd/mm/yyyy");



                    model.FirstLevelRanking = dsNetworkTree.Tables[0].Rows[0]["RANK"].ToString();
                    model.FirstLevelIntro = dsNetworkTree.Tables[0].Rows[0]["INTRO"].ToString();

BVA/BVA/Views/MemberShopCenter/InvoiceListing.cshtml
@using ECFBase.Components
@using resShared = ECFBase.Resources.OneForAll.OneForAll;
@using ECFBase.Models
@model PaginationInvoiceListingModel

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script type="text/javascript">

    $.ajaxSetup({ cache: false });
    $(document).ready(function () {

        $("#btnPage").click(function (evt) {
            var e = document.getElementById("page")
            var page = e.options[e.selectedIndex].value;
            $('#Loading').show();
            //ShowProgressAnimation();
            $.ajax({
                type: "POST",
                url: "/MemberShopCenter/InvoiceListing",
                data: { selectedPage: page},
                success: function (data) {
                    $("#main-content").html(data);
                   $('#Loading').hide();
                },
                error: function (xhr, status, error) {
                    var errorM = xhr.responseText;
                    errorM = errorM.replace('""', '');
                    alert(errorM);
                   $('#Loading').hide();
                }
            });
        });

        $(".ShowData").die() //must come in pair with .live if not multiple times will fired for that pop up dialog
        $(".ShowData").live("click", function (e) {
            e.preventDefault();
            var winH = 950;
            var winW = 1124;
            $("<div></div>")
            .addClass("modalEditCourse")
            .attr("id", $(this).attr("data_dialog_id"))
            .appendTo('#reportBS')
            .dialog({
                title: $(this).attr("data_dialog_title"),
                close: function () { $(this).remove(); },
                modal: true,
                height: winH,
                width: winW,
                resizable: false,
                //CKEDITOR cannot have "HIDE AND SHOW STYLE"
                //hide: "slide",
                //show: "slide",
                context: $(this)
            }).load(this.href);
            $(".ui-dialog").addClass("white-dialog");
        });
    });
</script>
<div id="reportBS">
    <div style="height: 30px; padding-left: 20px; text-align: left">
        <h3>
            @resShared.lblTransaction >> @resShared.lblInvoiceListing
        </h3>
    </div>
    <div class="grid" style="margin-left: 5px;" id="grid">
        <div class="grid">
            <table id="tablestyle" style="width: 100%">
                <thead>
                    <tr style="height: 25px; background-color: #f1f1f1; border-top: 2px solid white;">
                        <th style="width:40px;">
                            @resShared.lblNumber
                        </th>
                        <th style="width:70px;">
                            @resShared.lblInvoiceNo
                        </th>
                        <th style="width:150px">
                            @resShared.lblDate
                        </th>
                        <th style="width:110px">
                            @resShared.lblUsername
                        </th>
                        <th style="width:70px">
                            @resShared.lblType
                        </th>
                        <th style="width:70px">
                            @resShared.lblAmount
                        </th>
                        <th style="width:70px">
                            @resShared.lblStatus
                        </th>
                        <th style="width:80px">
                            @resShared.lblAction
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.InvoiceLists.Count == 0)
                    {
                        <tr style="height: 25px; border-top: 2px solid white;">
                            <td style="padding: 5px;" colspan="10">
                                @resShared.lblNoRecFound
                            </td>
                        </tr>
                    }
                    @foreach (var item in Model.InvoiceLists)
                    {                          
                        <tr>
                            <td align="center" style="text-align: center">
                                @Html.DisplayFor(modelItem => item.RowNumber)
                            </td>
                            <td align="center" style="text-align: center">
                             @*   @Html.HiddenFor(modelItem => item.InvoiceNo)
                                @Html.HiddenFor(modelItem => item.Id)
                                <a id="openDialogBB" style="float:right; text-decoration: underline; text-align: center" class="ShowData" data_dialog_title="@item.InvoiceNo : @item.Username" data_dialog_id="viewInvoice" 
                                   href="@Url.Action("InvoiceView", "MemberShopCenter", new { Id = item.Id })">*@
                                    @Html.DisplayFor(modelItem => item.InvoiceNo, new { @style = "text-decoration:underline; text-align: center" })                                                
                               @* </a>  *@        
                            </td>
                            <td align="center" style="text-align: center">
                                @Html.HiddenFor(modelItem => item.Date)
                                @Convert.ToDateTime(item.Date).ToString("dd/MM/yyyy hh:mm:ss tt")
                            </td>
                            <td align="center" style="text-align: center">
                                @Html.DisplayFor(modelItem => item.Username)
                            </td>
                            <td align="center" style="text-align: center">
                                @Html.DisplayFor(modelItem => item.InvoiceCashName)
                            </td>
                            <td align="center" style="text-align: center">
                                @Html.DisplayFor(modelItem => item.TotalAmount)
                            </td>
                            <td align="center" style="text-align: center">
                                @Misc.DeliveryStatus(item.Status)
                            </td>
                            <td align="center" style="width:60px; text-align: center">
                               @*<a style="text-decoration:underline;" id="@item.Id" class="EditData">
                                    @resShared.lblEdit 
                                </a>&nbsp;*@
                                <a href="@Url.Action("PrintInvoice", "MemberShopCenter", new { InvoiceID = item.Id })" target="_blank">@resShared.lblPrint</a>
                            </td>
                        </tr> 
                    }
                </tbody>
            </table>
            <table width="100%">
                <tr>
                    <td style="text-align: right">
                        <div class="BtnClass" style="float: right;">
                            @Html.DropDownList("page", @Model.Pages, new { style = "width:50px;" })
                            <input id="btnPage" value="@resShared.btnView" class="button" />
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>

BVA/BVA/Views/MemberShopCenter/MPRegisterNewMemberPage1.cshtml
@using ECFBase.Models
@using resShared = ECFBase.Resources.OneForAll.OneForAll;
@model RegisterNewMemberModel
@{
    ViewBag.Title = "MP RegisterNewMemberPage1";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<script type="text/javascript">      

    $("#btnNext").click(function (evt) {
        $.validator.unobtrusive.parse($('#regMem'));
        if (jQuery("#regMem").valid() == true) {
            $.ajax({
                type: "POST",
                url: "/MemberShopCenter/MPRegisterNewMemberPage1Method",
                data: $("#regMem").serialize(),
                success: function (data) {
                    $("#main-content").html(data);
                    $('#Loading').hide();
                },
                error: function (xhr, status, error) {
                    var errorM = xhr.responseText;
                    errorM = errorM.replace('""', '');
                    alert(errorM);
                    $('#Loading').hide();
                }
            });
        } return false;
    });

    $("#memberEmail").focusout(function (e) {
        $('#Loading').show();
        $.ajax({
            url: "/MemberShopCenter/MPRegisterNewMemberPage1",
            type: "POST",
            data: $("#regMem").serialize(),
            data: { Rank: $(document.getElementById("SelectedRank")).val(), upMember: $(document.getElementById("UsernameID")).val(), position: $(document.getElementById("Location")).val(), startFresh: false, MBintro: $(document.getElementById("MBintro")).val(), CountryCode: $(document.getElementById("SelectedCountry")).val() },
            success: function (data) {
                $("#main-content").html(data);
                $('#Loading').hide();

            },
            error: function (xhr, status, error) {
                var errorM = xhr.responseText;
                errorM = errorM.replace('""', '');
                alert(errorM);
                $('#Loading').hide();
            }

        });
    });

    $('#MBintro').focusout(function () {
        //Clear and get country code
        $.validator.unobtrusive.parse($('#regMem'));
        $('#Loading').show();
        $.ajax({
            url: "/MemberShopCenter/MPRegisterNewMemberPage1",
            type: "POST",
            data: $("#regMem").serialize(),
            data: {Rank: $(document.getElementById("SelectedRank")).val(), upMember: $(document.getElementById("UsernameID")).val(), position: $(document.getElementById("Location")).val(), startFresh: false ,MBintro: $(document.getElementById("MBintro")).val(), CountryCode: $(document.getElementById("SelectedCountry")).val()},
            success: function (data) {
                $("#main-content").html(data);
                $('#Loading').hide();
            },
            error: function (xhr, status, error) {
                var errorM = xhr.responseText;
                errorM = errorM.replace('""', '');
                alert(errorM);
                $('#Loading').hide();
            }
       
        });
    });

    $('#SelectedRank').change(function () {
        $.validator.unobtrusive.parse($('#regMem'));
        $('#Loading').show();
        $.ajax({
            type: "POST",
            url: "/MemberShopCenter/MPRegisterNewMemberPage1",
            data: $("#regMem").serialize(),
            data: { Rank: $(document.getElementById("SelectedRank")).val(), upMember: $(document.getElementById("UsernameID")).val(), position: $(document.getElementById("Location")).val(), startFresh: false ,MBintro: $(document.getElementById("MBintro")).val(),CountryCode: $(document.getElementById("SelectedCountry")).val()},
            success: function (data) {
                $("#main-content").html(data);
                $('#Loading').hide();
            },
            error: function (xhr, status, error) {
                var errorM = xhr.responseText;
                errorM = errorM.replace('""', '');
                alert(errorM);
                $('#Loading').hide();
            }
        });
    });

</script>

<div class="container-fluid">
    @{ Html.EnableClientValidation(true); }
    @using (Html.BeginForm("MPRegisterNewMemberPage3Method", "MemberShopCenter", FormMethod.Post, new { enctype = "multipart/form-data", name = "regMem", id = "regMem" })) //this id very important to do HttpPost
    {
        //display Model's errors
        @Html.ValidationSummary(true)
        <div class="row">
            <div class="col-lg-12">
                <ol class="breadcrumb default square rsaquo sm no-border">
                    <li><a href="javascript:;" id="Home"><i class="fa fa-home"></i></a></li>
                    <li><a href="#">@resShared.mnuTransaction</a></li>
                    <li><a href="#">@resShared.mnuPersonalSignup</a></li>
                    <li class="active"><a href="#">@resShared.lblUplineDetail</a></li>
                </ol>

                <h1 class="page-sub-header"></h1>
            </div>
        </div>
        <div class="col-lg-12" align="center">
            <div style="max-width: 600px; text-align: left">
                <div class="form-group">
                    <strong>@resShared.lblRegisterCountry</strong>

                    @Html.DropDownListFor(m => m.SelectedCountry, @Model.Countries, new { @id = "SelectedCountry", @class = "form-control" })
                    @Html.HiddenFor(m => m.SelectedCountry)
                </div>
            </div>
        </div>
        <div class="col-lg-12" align="center">
            <div style="max-width: 600px; text-align: left">
                <div class="form-group">


                    <strong>@resShared.lblUpline <span style="color: Red">*</span></strong>
                    @if (@Model.UsernameID == null)
                    {
                        @Html.TextBoxFor(m => @Model.Member.Upline, new { @class = "form-control" })
                    }
                    else
                    {

                        @Html.TextBoxFor(m => @Model.Member.Upline, new { @id = "UsernameID", @class = "form-control", @readonly = "readonly" })

                    }
                    <div style="margin-left: 0px;">
                        @Html.ValidationMessageFor(m => Model.UsernameID)
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-12" align="center">
            <div style="max-width: 600px; text-align: left">
                <div class="form-group">


                    <strong>@resShared.lblUplineDisplayName <span style="color: Red">*</span></strong>
                    @if (@Model.UsernameID == null)
                    {
                        @Html.TextBoxFor(m => @Model.UpLineFullName, new { @class = "form-control" })
                    }
                    else
                    {

                        @Html.TextBoxFor(m => @Model.UpLineFullName, new { @id = "UsernameID", @class = "form-control", @readonly = "readonly" })

                    }
                    <div style="margin-left: 0px;">
                        @Html.ValidationMessageFor(m => Model.UpLineFullName)
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-12" align="center">
            <div style="max-width: 600px; text-align: left">
                <div class="form-group">
                    <strong>@resShared.lblPosition <span style="color: Red">*</span></strong>
                    @if (@Model.UsernameID == null)
                    {
                        @Html.DropDownListFor(m => m.SelectedLocation, Model.Locations, new { @class = "form-control" })
                    }
                    else
                    {
                        @Html.HiddenFor(m => m.SelectedLocation)
                        @Html.DropDownListFor(m => m.SelectedLocation, Model.Locations, new { @id = "Location", @class = "form-control", @disabled = "disabled" })
                    }
                </div>
            </div>
        </div>
        <div class="col-lg-12" align="center">
            <div style="max-width: 600px; text-align: left">
                <div class="form-group">
                    <strong>@resShared.lblSponsorID <span style="color: Red">*</span></strong>

                    @Html.DropDownListFor(m => @Model.Member.SelectedOwnAccount, @Model.Member.OwnAccount, new { @id = "SelectedOwnAccount", @class = "form-control" })
                </div>
            </div>
        </div>
        <div class="col-lg-12" align="center">
            <div style="max-width: 600px; text-align: left">
                <div class="form-group">
                    <strong style="color:Red">@resShared.msgReg1</strong>
                </div>
            </div>
        </div>



        <div class="row" align="center">
            <div style="max-width: 600px;">
                <div class="form-group">
                    <button id="btnNext" type="button" class="btn btn-primary" style="width:100px">@resShared.btnNext >></button>
                </div>
            </div>
        </div>
    }
</div>

BVA/BVA/Views/MemberShopCenter/PrintInvoice.cshtml
<iframe style="border-style:none;text-align:center;" id="myReport" src="../../ReportsPDF/ReportingServices.aspx?ReportID=InvoiceReport&InvoiceID=@ViewBag.InvoiceID" width="100%" height="900px"></iframe>

BVA/BVA/Views/MemberShopCenter/SelfUpgradeMemberPage1.cshtml
@using ECFBase.Models
@using resShared = ECFBase.Resources.OneForAll.OneForAll;
@model RegisterNewMemberModel
@{
    ViewBag.Title = "RegisterNewMemberPage1";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script type="text/javascript">
    
    $("#btnNext").click(function (evt) {
        $.validator.unobtrusive.parse($('#regMem'));
        $('#Loading').show();
            $.ajax({
                type: "POST",
                url: "/MemberShopCenter/SelfUpgradeMemberPage1Method",                
                data: $("#regMem").serialize(),
                success: function (data) {
                    $("#main-content").html(data);
                   $('#Loading').hide();
                },
                error: function (xhr, status, error) {
                    var errorM = xhr.responseText;
                    errorM = errorM.replace('""', '');
                    alert(errorM);
                   $('#Loading').hide();
                }
            });
    });    
    
</script>

<div>
    @{ Html.EnableClientValidation(true); }
    @using (Html.BeginForm("SelfUpgradeMemberPage1Method", "MemberShopCenter", FormMethod.Post, new { enctype = "multipart/form-data", name = "regMem", id = "regMem" })) //this id very important to do HttpPost
    {
        //display Model's errors
        @Html.ValidationSummary(true)

    <div class="row">
        <div class="col-lg-12">
            <!-- Begin breadcrumb -->
            <ol class="breadcrumb default square rsaquo sm no-border" style="margin:10px;">
                <li><a href="javascript:;" id="Home"><i class="fa fa-home"></i></a></li>
                <li><a href="#">@resShared.mnuTransaction</a></li>
                <li><a href="#">@resShared.mnuPersonalUpgrade</a></li>
            </ol>
            <!-- End breadcrumb -->
            <h1 class="page-sub-header"></h1>
        </div>


        <div class="col-lg-12" align="center">
            <div style="max-width: 600px; text-align: left">
                <div class="form-group">
                    <strong>@resShared.lblUserID</strong>
                    @Html.TextBoxFor(m => @Model.Member.SelectedOwnAccount, new { @class = "form-control", disabled = "disabled", @id = "SelectedOwnAccount" })
                </div>
            </div>
        </div>

        <div class="col-lg-12" align="center">
            <div style="max-width: 600px; text-align: left">
                <div class="form-group">
                    <strong>@resShared.lblName</strong>
                    @Html.TextBoxFor(m => @Model.Member.FirstName, new { @class = "form-control", disabled = "disabled", @id = "FirstName" })
                </div>
            </div>
        </div>

        <div class="col-lg-12" align="center">
            <div style="max-width: 600px; text-align: left">
                <div class="form-group">
                    <strong>@resShared.lblRank</strong>
                    @Html.TextBoxFor(m => @Model.Member.Rank, new { @class = "form-control", disabled = "disabled", @id = "Rank" })
                </div>
            </div>
        </div>

        <div class="col-lg-12" align="center">
            <div style="max-width: 600px; text-align: left">
                <div class="form-group">
                    <strong>@resShared.lblCountry</strong>

                    @Html.DropDownListFor(m => m.SelectedCountry, @Model.Countries, new { @id = "SelectedCountry", @class = "form-control", disabled = "disabled" })
                    @Html.HiddenFor(m => m.SelectedCountry)
                </div>
            </div>
        </div>

        <div style=" height:30px">

        </div>

        <div class="col-lg-12" align="center">
            <div style="max-width: 600px;">
                <div class="form-group">
                    <button id="btnNext" type="button" class="btn btn-primary" style="width:100px">@resShared.btnNext >></button>
                </div>
            </div>
        </div>

    </div>

    }
</div>